services:
  - type: web
    name: my-cash-book-fe
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main
